[package]
name = "budgietlib"
description = "Bundled library for the native apps to call on"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "budgiet"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { version = "0.32.0", features = ["cli"] }
chrono = { workspace = true }
itertools = { workspace = true }
num-format = "0.4.4"
regex = "1.12.4"
rust_decimal = "1.42.1"
rusty-money = "=0.5.0"
serde = "1.0.228"
thiserror = "2.0.18"
tokio = { version = "1.53.0", features = ["sync", "fs", "rt-multi-thread"] }
unicode-segmentation = "1.13.3"
async-trait = "0.1.91"
